name: Relative Strength Rotator (5x/day)

on:
  schedule:
    - cron: "0 4 * * *"
    - cron: "0 8 * * *"
    - cron: "0 12 * * *"
    - cron: "0 16 * * *"
    - cron: "0 20 * * *"
  workflow_dispatch: {}

permissions:
  contents: write   # lai var ielikt 'last_top.json' izmaiņas repo

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run rotator
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
          WATCHLIST_MODE: TOP100
          MIN_24H_VOLUME_USD: "50000000"
          MIN_24H_PCT: "3.0"
          MA_PERIOD: "20"
          RSI_THRESHOLD: "55"
          ATR_PCT_MIN: "1.5"
          TIMEFRAME: "1h"
          TOP_N: "5"
          LANGUAGE: "LV"
          SHORT_FORMAT: "true"
          ADVICE_ENABLED: "true"    # ja gribi bez entry/SL/TP rindām -> ieliec false
        run: |
          python main.py

      - name: Commit state if changed
        run: |
          if [[ -n "$(git status --porcelain last_top.json)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add last_top.json
            git commit -m "Update last_top.json (auto)"
            git push
          else
            echo "No changes in last_top.json"
          fi
