name: Relative Strength Rotator (5x/day)

on:
  schedule:
    # 07:00, 11:00, 15:00, 19:00, 23:00 Rīga (vasarā UTC+3 → zemāk UTC)
    - cron: "0 4 * * *"
    - cron: "0 8 * * *"
    - cron: "0 12 * * *"
    - cron: "0 16 * * *"
    - cron: "0 20 * * *"
  workflow_dispatch: {}

permissions:
  contents: write   # lai varam komitēt last_top.json izmaiņas

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run rotator
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
          WATCHLIST_MODE: TOP100
          # bāzes sliekšņi (paliek kā bija)
          MIN_24H_VOLUME_USD: "50000000"
          MIN_24H_PCT: "3.0"
          MA_PERIOD: "20"
          RSI_THRESHOLD: "55"
          ATR_PCT_MIN: "1.5"
          TIMEFRAME: "1h"
          TOP_N: "5"
          LANGUAGE: "LV"
          SHORT_FORMAT: "true"
          LONG_FORMAT: "true"      # ⬅ ieslēdz garo formātu
          DETAIL_EMOJI: "true"     # ⬅ bultiņas ↑/↓/=
          ADVICE_ENABLED: "true"

          # (pēc vajadzības) TF-spec sliekšņi, piem. 4h stingrāks RSI:
          # RSI_THRESHOLD_4H: "58"
          # MIN_24H_PCT_4H: "2.0"
          # ATR_PCT_MIN_4H: "1.2"

        run: |
          python main.py

     
